pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
    stages {
        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/hardikpt/https://github.com/hardikpt/AndroidStudioWebApp.git'
            }
        }
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
